Spec.describe 'Spec.DSL', ->
  describe 'describe'
  describe 'before'
  describe 'expect.to'
  describe 'expect.notTo'
  describe 'given'
  describe 'it'
  describe 'pending'
  describe 'its'
  describe 'should'
  describe 'shouldNot'
  describe 'mock'
  describe 'subject'
  describe 'context'
  describe 'specify'
